analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
linter:
  rules:
    - annotate_overrides
    - avoid_init_to_null
    - camel_case_types
    - constant_identifier_names
    #- unnecessary_new
    #- unnecessary_const
