name: rikulo_security
version: 1.1.2+1
description: > 
  A lightweight and highly customizable authentication and access-control framework for Rikulo Stream.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: https://github.com/rikulo/security
documentation: https://www.dartdocs.org/documentation/rikulo_security/1.1.2
dependencies:
  stream: ">=1.0.0 <3.0.0"
  rikulo_commons: '>=3.0.0 <5.0.0'
environment:
  sdk: ">=2.0.0 <3.0.0"
