name: rikulo_security
version: 2.5.0
description: > 
  A lightweight and highly customizable authentication and access-control framework for Rikulo Stream.
homepage: https://github.com/rikulo/security
documentation: https://pub.dev/documentation/rikulo_security/latest/
dependencies:
  stream: any
  rikulo_commons: any
environment:
  sdk: ">=3.0.0 <4.0.0"
