name: rikulo_security
version: 1.0.2
description: > 
  A lightweight and highly customizable authentication and access-control framework for Rikulo Stream.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org/projects/stream
documentation: http://docs.rikulo.org/stream/latest/Add-ons/Rikulo_Security/
dependencies:
  stream: any
environment:
  sdk: ">=2.0.0-dev <3.0.0"
