//Auto-generated by RSP Compiler
//Source: C:\home\tomyeh\prj\r\security\example\dummy\login.rsp.html
part of hello_security;

/** Template, login, for rendering the view. */
Future login(HttpConnect connect) { //#2
  var _cs_ = new List<HttpConnect>(), request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = new ContentType.fromString("""text/html; charset=utf-8""");

  response.write("""
<!DOCTYPE html>
<html>
  <head>
    <title>Sign in</title>
    <link href="/theme.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
  	<h1>Sign in</h1>
    <form action="/s_login">
      <p>Username</p>
      <p><input name="username" type="text" autofocus="true" size="30"/></p>
      <p>Password</p>
      <p><input name="password" type="password" size="30"/></p>
      <p><button type="submit">Sign in</button></p>
    </form>
	</p>
  </body>
</html>
"""); //#2

  return $nnf();
}
