//Auto-generated by RSP Compiler
//Source: home.rsp.html
part of hello_security;

/** Template, home, for rendering the view. */
Future home(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  response.write("""<!DOCTYPE html>
<html>
  <head>
    <title>Hello Rikulo Security</title>
    <link href="theme.css" rel="stylesheet" type="text/css" />
    <meta http-equiv="cache-control" content="no-cache">
  </head>
  <body>
  	<h1>Hello Rikulo Security</h1>
    <h2>Welcome, """);

  response.write(Rsp.nnx(currentUser(connect.request.session) != null ? currentUser(connect.request.session): "Stranger"));


  response.write("""</p>
    <ul>
      <li><a href="/member">Access the protected resource</a></li>
      <li><a href="/admin">Access the protected resource that requires administrator.</a></li>
    </ul>
  </body>
</html>
""");

  return null;
}
