//Auto-generated by RSP Compiler
//Source: login.rsp.html
part of hello_security;

/** Template, login, for rendering the view. */
Future login(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>(),
  request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = ContentType.parse("""text/html; charset=utf-8""");

  response.write("""
<!DOCTYPE html>
<html>
  <head>
    <title>Sign in</title>
    <link href="/theme.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
  	<h1>Sign in</h1>
"""); //#2

  if (request.uri.queryParameters["retry"] != null) { //if#10

    response.write("""
    <div class="error">Incorrect username or password.</div>
"""); //#11
  } //if

  response.write("""
    <form action="/s_login" method="post" accept-charset="UTF-8">
      Username<br/>
      <input name="s_username" type="text" autofocus="true" size="30"/><br/>
      Password<br/>
      <input name="s_password" type="password" size="30"/>
      <p><button type="submit">Sign in</button></p>
    </form>
	  <p>Usernames for testing: john (a normal user) and admin (an administrator). The password is 123.</p>
  </body>
</html>
"""); //#13

  return Rsp.nnf();
}
